<?php

return [
    'user'                      => '/user',
    'resetApiToken'             => '/user/reset_api_token',
    'companiesList'             => '/companies',
    'company'                   => '/companies/{companyId}',
    'companyInbox'              => '/companies/{companyId}/inboxes',
    'inboxesList'               => '/inboxes',
    'inbox'                     => '/inboxes/{inboxId}',
    'clean'                     => '/inboxes/{inboxId}/clean',
    'allRead'                   => '/inboxes/{inboxId}/all_read',
    'resetCredentials'          => '/inboxes/{inboxId}/reset_credentials',
    'resetEmailUsername'        => '/inboxes/{inboxId}/reset_email_username',
    'toggleEmailUsername'       => '/inboxes/{inboxId}/toggle_email_username',
    'sharedInboxesList'         => '/sharedInboxes',
    'sharedInbox'               => '/sharedInboxes/{sharedInboxId}',
    'messagesList'              => '/inboxes/{inboxId}/messages',
    'message'                   => '/inboxes/{inboxId}/messages/{messageId}',
    'forwardMessage'            => '/inboxes/{inboxId}/messages/{messageId}/forward',
    'messageBodyHtml'           => '/inboxes/{inboxId}/messages/{messageId}/body.html',
    'messageBodyText'           => '/inboxes/{inboxId}/messages/{messageId}/body.txt',
    'messageBodyRaw'            => '/inboxes/{inboxId}/messages/{messageId}/body.raw',
    'messageBodyEml'            => '/inboxes/{inboxId}/messages/{messageId}/body.eml',
    'messageMailHeaders'        => '/inboxes/{inboxId}/messages/{messageId}/mail_headers',
    'messageSpamReport'         => '/inboxes/{inboxId}/messages/{messageId}/spam_report',
    'messageAnalyze'            => '/inboxes/{inboxId}/messages/{messageId}/analyze',
    'messageAttachmentsList'    => '/inboxes/{inboxId}/messages/{messageId}/attachments',
    'messageAttachment'         => '/inboxes/{inboxId}/messages/{messageId}/attachments/{attachmentId}',
    'messageForwardRules'       => '/inboxes/{inboxId}/forward_rules',
    'messageForwardRule'        => '/inboxes/{inboxId}/forward_rules/{forwardRuleId}',
    'inboxUsersList'            => '/inboxes/{inboxId}/inboxes_users',
    'inboxUser'                 => '/inboxes/{inboxId}/inboxes_users/{inboxUserId}',
    'corsDomains'               => '/cors_domains',
    'corsDomain'                => '/cors_domains/{corsDomainId}',
    'sharedUsersList'           => '/companies/{companyId}/shared_users',
    'sharedUser'                => '/companies/{companyId}/shared_users/{sharedUserId}',
];
